Add convert_charrefs field to TagStrip
Newer python versions expect this:

ERROR: Diff process exited with an error
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/htmldiff/entry_point.py", line 116, in diff
    diffed_html = gen_side_by_side(diffed_html)
  File "/usr/lib/python3.7/site-packages/htmldiff/lib.py", line 412, in gen_side_by_side
    left = span_to_whitespace(left_side, 'insert')
  File "/usr/lib/python3.7/site-packages/htmldiff/lib.py", line 383, in span_to_whitespace
    stripped = strip_tags(strip)
  File "/usr/lib/python3.7/site-packages/htmldiff/lib.py", line 65, in strip_tags
    st.feed(html_string)
  File "/usr/lib/python3.7/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib/python3.7/html/parser.py", line 139, in goahead
    if self.convert_charrefs and not self.cdata_elem:
AttributeError: 'TagStrip' object has no attribute 'convert_charrefs'